package accounting

import "github.com/buchfink/buchfink/internal/models"

// DefaultSKR04Accounts returns a curated, production-grade list of SKR04 accounts
// suitable for small businesses and self-employed professionals with clear explanations.
func DefaultSKR04Accounts() []models.Account {
	return []models.Account{
		// -------------------------------------------------------------
		// KLASSE 0: ANLAGEVERMÖGEN (Assets - Non-current)
		// -------------------------------------------------------------
		{
			Number:      "0520",
			Name:        "EDV-Software / Lizenzen",
			Type:        "asset",
			Category:    "Immaterielle Vermögensgegenstände",
			TaxRate:     0.0,
			Description: "Gekaufte Softwarelizenzen, Domains, geistiges Eigentum.",
			IsActive:    true,
		},
		{
			Number:      "0650",
			Name:        "Büroeinrichtung",
			Type:        "asset",
			Category:    "Sachanlagen",
			TaxRate:     0.0,
			Description: "Schreibtische, Bürostühle, Lampen und sonstige Einrichtung.",
			IsActive:    true,
		},
		{
			Number:      "0670",
			Name:        "Geringwertige Wirtschaftsgüter (GWG)",
			Type:        "asset",
			Category:    "Sachanlagen",
			TaxRate:     0.0,
			Description: "Gegenstände zwischen 250 € und 800 € netto (Sofortabschreibung).",
			IsActive:    true,
		},
		{
			Number:      "0675",
			Name:        "GWG Sammelposten (Pool)",
			Type:        "asset",
			Category:    "Sachanlagen",
			TaxRate:     0.0,
			Description: "Sammelposten für Wirtschaftsgüter zwischen 250 € und 1.000 €.",
			IsActive:    true,
		},
		{
			Number:      "0680",
			Name:        "Computer, Laptops & Server",
			Type:        "asset",
			Category:    "Sachanlagen",
			TaxRate:     0.0,
			Description: "Computerhardware, Notebooks, Peripheriegeräte.",
			IsActive:    true,
		},
		{
			Number:      "0800",
			Name:        "Beteiligungen an verbundenen Unternehmen",
			Type:        "asset",
			Category:    "Finanzanlagen",
			TaxRate:     0.0,
			Description: "Unternehmensanteile, Beteiligungen, Aktien.",
			IsActive:    true,
		},

		// -------------------------------------------------------------
		// KLASSE 1: UMLAUFVERMÖGEN (Assets - Current)
		// -------------------------------------------------------------
		{
			Number:      "1200",
			Name:        "Forderungen aus Lieferungen und Leistungen",
			Type:        "asset",
			Category:    "Forderungen",
			TaxRate:     0.0,
			Description: "Sammelkonto für unbezahlte Ausgangsrechnungen an Kunden.",
			IsActive:    true,
		},
		{
			Number:      "1400",
			Name:        "Abziehbare Vorsteuer 19%",
			Type:        "asset",
			Category:    "Steuerforderungen",
			TaxRate:     0.19,
			Description: "Vorsteuer aus Eingangsrechnungen mit 19% MwSt.",
			IsActive:    true,
		},
		{
			Number:      "1401",
			Name:        "Abziehbare Vorsteuer 7%",
			Type:        "asset",
			Category:    "Steuerforderungen",
			TaxRate:     0.07,
			Description: "Vorsteuer aus Eingangsrechnungen mit 7% MwSt. (Bücher, Lebensmittel).",
			IsActive:    true,
		},
		{
			Number:      "1600",
			Name:        "Kasse / Bargeld",
			Type:        "asset",
			Category:    "Liquide Mittel",
			TaxRate:     0.0,
			Description: "Bargeldbestand im Unternehmen.",
			IsActive:    true,
		},
		{
			Number:      "1800",
			Name:        "Bankkonto (Geschäftskonto)",
			Type:        "asset",
			Category:    "Liquide Mittel",
			TaxRate:     0.0,
			Description: "Haupt-Geschäftskonto bei Ihrer Hausbank.",
			IsActive:    true,
		},
		{
			Number:      "1810",
			Name:        "Bankkonto 2 / Sparkonto",
			Type:        "asset",
			Category:    "Liquide Mittel",
			TaxRate:     0.0,
			Description: "Zweites Bankkonto, Tagesgeld oder Unterkonto.",
			IsActive:    true,
		},
		{
			Number:      "1820",
			Name:        "Zahlungsdienstleister (Stripe / PayPal)",
			Type:        "asset",
			Category:    "Liquide Mittel",
			TaxRate:     0.0,
			Description: "Guthaben auf Stripe-, PayPal- oder Online-Payment-Accounts.",
			IsActive:    true,
		},
		{
			Number:      "1900",
			Name:        "Aktive Rechnungsabgrenzung (ARAP)",
			Type:        "asset",
			Category:    "Rechnungsabgrenzung",
			TaxRate:     0.0,
			Description: "Ausgaben im alten Jahr, die wirtschaftlich das neue Jahr betreffen.",
			IsActive:    true,
		},

		// -------------------------------------------------------------
		// KLASSE 2: EIGENKAPITAL & RÜCKSTELLUNGEN (Equity & Liabilities)
		// -------------------------------------------------------------
		{
			Number:      "2000",
			Name:        "Gezeichnetes Kapital / Stammkapital",
			Type:        "liability",
			Category:    "Eigenkapital",
			TaxRate:     0.0,
			Description: "Stammkapital der GmbH/UG oder Grundkapital.",
			IsActive:    true,
		},
		{
			Number:      "2100",
			Name:        "Privatkonto (Einlagen / Entnahmen)",
			Type:        "liability",
			Category:    "Eigenkapital",
			TaxRate:     0.0,
			Description: "Private Einlagen und Entnahmen bei Einzelunternehmen / Personengesellschaften.",
			IsActive:    true,
		},
		{
			Number:      "2868",
			Name:        "Saldenvorträge Sachkonten (Vortragskonto)",
			Type:        "liability",
			Category:    "Eröffnungskonten",
			TaxRate:     0.0,
			Description: "Hilfskonto für Eröffnungsbilanzbuchungen zu Jahresbeginn.",
			IsActive:    true,
		},
		{
			Number:      "2900",
			Name:        "Gewinnvortrag vor Verwendung",
			Type:        "liability",
			Category:    "Eigenkapital",
			TaxRate:     0.0,
			Description: "Jahresüberschuss vergangener Geschäftsjahre.",
			IsActive:    true,
		},

		// -------------------------------------------------------------
		// KLASSE 3: VERBINDLICHKEITEN (Liabilities - Current)
		// -------------------------------------------------------------
		{
			Number:      "3300",
			Name:        "Verbindlichkeiten aus Lieferungen und Leistungen",
			Type:        "liability",
			Category:    "Verbindlichkeiten",
			TaxRate:     0.0,
			Description: "Sammelkonto für offene Eingangsrechnungen von Lieferanten.",
			IsActive:    true,
		},
		{
			Number:      "3806",
			Name:        "Umsatzsteuer 19%",
			Type:        "liability",
			Category:    "Steuerverbindlichkeiten",
			TaxRate:     0.19,
			Description: "Umsatzsteuer aus eigenen Verkäufen mit 19% MwSt.",
			IsActive:    true,
		},
		{
			Number:      "3801",
			Name:        "Umsatzsteuer 7%",
			Type:        "liability",
			Category:    "Steuerverbindlichkeiten",
			TaxRate:     0.07,
			Description: "Umsatzsteuer aus Verkäufen mit ermäßigtem Steuersatz 7%.",
			IsActive:    true,
		},
		{
			Number:      "3820",
			Name:        "Umsatzsteuer-Vorauszahlungen (Finanzamt)",
			Type:        "liability",
			Category:    "Steuerverbindlichkeiten",
			TaxRate:     0.0,
			Description: "An das Finanzamt gezahlte oder erstattete USt-Vorauszahlungen.",
			IsActive:    true,
		},

		// -------------------------------------------------------------
		// KLASSE 4: BETRIEBLICHE ERTRÄGE (Revenue)
		// -------------------------------------------------------------
		{
			Number:      "4400",
			Name:        "Erlöse 19% USt",
			Type:        "revenue",
			Category:    "Umsatzerlöse",
			TaxRate:     0.19,
			Description: "Reguläre Umsätze und Dienstleistungen mit 19% deutscher Umsatzsteuer.",
			IsActive:    true,
		},
		{
			Number:      "4300",
			Name:        "Erlöse 7% USt",
			Type:        "revenue",
			Category:    "Umsatzerlöse",
			TaxRate:     0.07,
			Description: "Ermäßigte Umsätze mit 7% Mehrwertsteuer.",
			IsActive:    true,
		},
		{
			Number:      "4120",
			Name:        "Steuerfreie Umsätze (§ 4 Nr. 8 ff. UStG)",
			Type:        "revenue",
			Category:    "Umsatzerlöse",
			TaxRate:     0.0,
			Description: "Steuerfreie Umsätze ohne Vorsteuerabzugsberechtigung.",
			IsActive:    true,
		},
		{
			Number:      "4125",
			Name:        "Steuerfreie innergemeinschaftliche Lieferungen (EU)",
			Type:        "revenue",
			Category:    "Umsatzerlöse",
			TaxRate:     0.0,
			Description: "B2B-Verkäufe an Kunden im EU-Ausland mit gültiger USt-IdNr.",
			IsActive:    true,
		},
		{
			Number:      "4130",
			Name:        "Steuerfreie Ausfuhren (Drittland / Non-EU)",
			Type:        "revenue",
			Category:    "Umsatzerlöse",
			TaxRate:     0.0,
			Description: "Exporte in Länder außerhalb der EU (z.B. Schweiz, USA).",
			IsActive:    true,
		},
		{
			Number:      "4830",
			Name:        "Sonstige betriebliche Erträge",
			Type:        "revenue",
			Category:    "Nebenerlöse",
			TaxRate:     0.0,
			Description: "Nebeneinnahmen, Rückerstattungen, Schadensersatzzahlungen.",
			IsActive:    true,
		},

		// -------------------------------------------------------------
		// KLASSE 6: BETRIEBLICHE AUFWENDUNGEN (Expenses)
		// -------------------------------------------------------------
		{
			Number:      "6300",
			Name:        "Löhne und Gehälter",
			Type:        "expense",
			Category:    "Personalaufwand",
			TaxRate:     0.0,
			Description: "Bruttogehälter der Angestellten.",
			IsActive:    true,
		},
		{
			Number:      "6400",
			Name:        "Fremdleistungen / Subunternehmer",
			Type:        "expense",
			Category:    "Fremdleistungen",
			TaxRate:     0.19,
			Description: "Eingekaufte Dienstleistungen von Freelancern und Subunternehmern.",
			IsActive:    true,
		},
		{
			Number:      "6500",
			Name:        "Miete & Nebenkosten (Büro / Geschäftsräume)",
			Type:        "expense",
			Category:    "Raumkosten",
			TaxRate:     0.0,
			Description: "Gezahlte Büromiete, Coworking-Gebühren, Nebenkosten.",
			IsActive:    true,
		},
		{
			Number:      "6800",
			Name:        "Porto, Telefon, Internet, SaaS",
			Type:        "expense",
			Category:    "Kommunikation & IT",
			TaxRate:     0.19,
			Description: "Internetanschluss, Handyverträge, Cloud-Software, Hosting.",
			IsActive:    true,
		},
		{
			Number:      "6815",
			Name:        "Bürobedarf",
			Type:        "expense",
			Category:    "Betriebsbedarf",
			TaxRate:     0.19,
			Description: "Papier, Stifte, Kaffeebedarf fürs Büro, Kleinstmaterial.",
			IsActive:    true,
		},
		{
			Number:      "6825",
			Name:        "Rechts- und Steuerberatung, Buchführung",
			Type:        "expense",
			Category:    "Beratung",
			TaxRate:     0.19,
			Description: "Steuerberaterkosten, Anwaltshonorare, Notargebühren.",
			IsActive:    true,
		},
		{
			Number:      "6830",
			Name:        "Buchführungskosten & Software",
			Type:        "expense",
			Category:    "Verwaltung",
			TaxRate:     0.19,
			Description: "Softwarelizenzen für Buchhaltung und Verwaltung.",
			IsActive:    true,
		},
		{
			Number:      "6850",
			Name:        "Werbung & Marketing",
			Type:        "expense",
			Category:    "Marketing",
			TaxRate:     0.19,
			Description: "Google Ads, Meta Ads, Messen, Flyer, Webdesign.",
			IsActive:    true,
		},
		{
			Number:      "6855",
			Name:        "Reisekosten (Fahrt, Hotel, Spesen)",
			Type:        "expense",
			Category:    "Reisekosten",
			TaxRate:     0.19,
			Description: "Bahn- und Flugtickets, Übernachtungskosten, Verpflegungspauschalen.",
			IsActive:    true,
		},
		{
			Number:      "6860",
			Name:        "Bewirtungskosten 70% (geschäftlich)",
			Type:        "expense",
			Category:    "Repräsentation",
			TaxRate:     0.19,
			Description: "Geschäftsessen mit Kunden (70% abziehbarer Anteil).",
			IsActive:    true,
		},
		{
			Number:      "6865",
			Name:        "Nicht abziehbare Bewirtungskosten (30%)",
			Type:        "expense",
			Category:    "Repräsentation",
			TaxRate:     0.0,
			Description: "30% Eigenanteil bei geschäftlichen Bewirtungen.",
			IsActive:    true,
		},
		{
			Number:      "6870",
			Name:        "Nebenkosten des Geldverkehrs / Bankgebühren",
			Type:        "expense",
			Category:    "Finanzkosten",
			TaxRate:     0.0,
			Description: "Kontoführungsgebühren, Stripe/PayPal-Transaktionsgebühren.",
			IsActive:    true,
		},
		{
			Number:      "6900",
			Name:        "Abschreibungen auf Sachanlagen (AfA)",
			Type:        "expense",
			Category:    "Abschreibungen",
			TaxRate:     0.0,
			Description: "Reguläre jährliche Abschreibung für Computer, Möbel etc.",
			IsActive:    true,
		},
	}
}
