package accounting

// positionTargets ordnet jede der 206 Positionen des SKR04 einer
// Gliederungsposition nach §§ 266, 275 HGB zu.
//
// Die Tabelle ist vollständig und wird von statement_test.go gegen den Katalog
// geprüft: eine Position ohne Ziel hieße, dass ein Konto im Abschluss
// verschwindet. Wo der SKR04 einen Posten „X oder Y" nennt — dieselben Konten
// sind Forderung oder Verbindlichkeit, je nach Saldo —, steht die Gegenposition
// in AltKey.
//
// Die Zuordnung folgt der Gliederung der Kapitalgesellschaft. Positionen der
// Personenhandelsgesellschaft und der Genossenschaft landen auf der Zeile, die
// ihnen wirtschaftlich entspricht, und tragen dazu einen Hinweis; ohne ihn
// stünde ein Kapitalkonto der KG kommentarlos unter dem gezeichneten Kapital.
//
// Maßgeblich ist der Inhalt der Konten, nicht der Name der Katalogposition.
// Im SKR04-Katalog sind Name, hgb_code und category mehrerer Positionen um eine
// Zeile verschoben: „guv.guv_7_a.soziale_abgaben…" führt die Konten 6200 bis
// 6231 (Abschreibungen), „guv.guv_3.andere_aktivierte_eigenleistungen" die
// Konten 4700 ff. (Erlösschmälerungen), „guv.guv_4.umsatzerloese" die Konten
// 4833 ff. (sonstige betriebliche Erträge) und „bilanz.passiva_a_iii.
// anfangskapital" die Konten 2963 ff. (Gewinnrücklagen aus den
// Übergangsvorschriften des BilMoG). Wer hier dem Namen folgt, weist
// Abschreibungen als Personalaufwand aus. Die Zuordnung folgt deshalb den
// Kontennummern; statement_test.go prüft das für Stichproben jeder Kontenklasse.
var positionTargets = map[string]positionTarget{
	"bilanz.aktiva_ausstehendeeinlagen.nicht_eingeforderte_ausstehende_einlagen":                {Key: "aktiva.0"},
	"bilanz.aktiva_ausstehendeeinlagen.eingeforderte_noch_ausstehende_kapitalei":                {Key: "aktiva.B.II.4", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.aktiva_ausstehendeeinlagen.rueckstaendige_faellige_einzahlungen_auf":                {Key: "aktiva.B.II.4"},
	"bilanz.aktiva_a_i.entgeltlich_erworbene_konzessionen_gewer":                                {Key: "aktiva.A.I.2"},
	"bilanz.aktiva_a_i.selbst_geschaffene_gewerbliche_schutzrec":                                {Key: "aktiva.A.I.1"},
	"bilanz.aktiva_a_i.in_der_entwicklung_befindliche_immaterie":                                {Key: "aktiva.A.I.1"},
	"bilanz.aktiva_a_i.geschaefts_oder_firmenwert":                                              {Key: "aktiva.A.I.3"},
	"bilanz.aktiva_a_i.geleistete_anzahlungen":                                                  {Key: "aktiva.A.I.4"},
	"bilanz.aktiva_a_ii.grundstuecke_grundstuecksgleiche_rechte":                                {Key: "aktiva.A.II.1"},
	"bilanz.aktiva_a_ii.technische_anlagen_und_maschinen":                                       {Key: "aktiva.A.II.2"},
	"bilanz.aktiva_a_ii.andere_anlagen_betriebs_und_geschaeftsau":                               {Key: "aktiva.A.II.3"},
	"bilanz.aktiva_a_ii.geleistete_anzahlungen_und_anlagen_im_ba":                               {Key: "aktiva.A.II.4"},
	"bilanz.aktiva_a_iii.anteile_an_verbundenen_unternehmen":                                    {Key: "aktiva.A.III.1"},
	"bilanz.aktiva_a_iii.ausleihungen_an_verbundene_unternehmen":                                {Key: "aktiva.A.III.2"},
	"bilanz.aktiva_a_iii.beteiligungen":                                                         {Key: "aktiva.A.III.3"},
	"bilanz.aktiva_a_iii.ausleihungen_an_unternehmen_mit_denen_ei":                              {Key: "aktiva.A.III.4"},
	"bilanz.aktiva_a_iii.wertpapiere_des_anlagevermoegens":                                      {Key: "aktiva.A.III.5"},
	"bilanz.aktiva_a_iii.sonstige_ausleihungen":                                                 {Key: "aktiva.A.III.6"},
	"bilanz.aktiva_a_iii.ausleihungen_an_gesellschafter":                                        {Key: "aktiva.A.III.6"},
	"bilanz.aktiva_a_iii.genossenschaftsanteile":                                                {Key: "aktiva.A.III.3"},
	"bilanz.aktiva_a_iii.rueckdeckungsansprueche_aus_lebensversic":                              {Key: "aktiva.A.III.6"},
	"bilanz.aktiva_b_i.roh_hilfs_und_betriebsstoffe":                                            {Key: "aktiva.B.I.1"},
	"bilanz.aktiva_b_i.unfertige_erzeugnisse_unfertige_leistung":                                {Key: "aktiva.B.I.2"},
	"bilanz.aktiva_b_i.in_ausfuehrung_befindliche_bauauftraege":                                 {Key: "aktiva.B.I.2"},
	"bilanz.aktiva_b_i.in_arbeit_befindliche_auftraege":                                         {Key: "aktiva.B.I.2"},
	"bilanz.aktiva_b_i.fertige_erzeugnisse_und_waren":                                           {Key: "aktiva.B.I.3"},
	"bilanz.aktiva_b_i.geleistete_anzahlungen":                                                  {Key: "aktiva.B.I.4"},
	"bilanz.aktiva_b_i.erhaltene_anzahlungen_auf_bestellungen_v":                                {Key: "passiva.C.3", Note: "Erhaltene Anzahlungen auf Bestellungen; § 268 Abs. 5 Satz 2 HGB lässt den offenen Absatz von den Vorräten zu, Buchfink weist sie unter den Verbindlichkeiten aus."},
	"bilanz.aktiva_b_ii.forderungen_aus_lieferungen_und_leistung":                               {Key: "aktiva.B.II.1", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.forderungen_und_sonstige_vermoegensgegen":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.andere_forderungen_gegen_gesellschafter":                                {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.forderungen_gegen_verbundene_unternehmen":                               {Key: "aktiva.B.II.2", AltKey: "passiva.C.6"},
	"bilanz.aktiva_b_ii.forderungen_gegen_unternehmen_mit_denen":                                {Key: "aktiva.B.II.3", AltKey: "passiva.C.7"},
	"bilanz.aktiva_b_ii.eingeforderte_noch_ausstehende_kapitalei":                               {Key: "aktiva.B.II.4"},
	"bilanz.aktiva_b_ii.eingeforderte_nachschuesse":                                             {Key: "aktiva.B.II.4"},
	"bilanz.aktiva_b_ii.sonstige_vermoegensgegenstaende_oder_son":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.sonstige_vermoegensgegenstaende":                                        {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.forderungen_gegen_gesellschafter_oder_ve":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_ii.forderungen_gegen_persoenlich_haftende_g":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.aktiva_b_ii.forderungen_gegen_kommanditisten_oder_ve":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.aktiva_b_ii.aktiver_unterschiedsbetrag_aus_der_vermo":                               {Key: "aktiva.E", AltKey: "passiva.B.3"},
	"bilanz.aktiva_b_ii.aktiver_unterschiedsbetrag_aus_vermoegen":                               {Key: "aktiva.E", AltKey: "passiva.B.3"},
	"bilanz.aktiva_b_ii.sonstige_verbindlichkeiten_oder_sonstige":                               {Key: "aktiva.B.II.4", AltKey: "passiva.C.8"},
	"bilanz.aktiva_b_iii.anteile_an_verbundenen_unternehmen":                                    {Key: "aktiva.B.III.1"},
	"bilanz.aktiva_b_iii.sonstige_wertpapiere":                                                  {Key: "aktiva.B.III.2"},
	"bilanz.aktiva_b_iii.kassenbestand_bundesbankguthaben_guthabe":                              {Key: "aktiva.B.IV", AltKey: "passiva.C.2"},
	"bilanz.aktiva_b_iv.kassenbestand_bundesbankguthaben_guthabe":                               {Key: "aktiva.B.IV", AltKey: "passiva.C.2"},
	"bilanz.aktiva_b_iv.verbindlichkeiten_gegenueber_kreditinsti":                               {Key: "aktiva.B.IV", AltKey: "passiva.C.2"},
	"bilanz.aktiva_c.rechnungsabgrenzungsposten":                                                {Key: "aktiva.C"},
	"bilanz.aktiva_c.aktive_latente_steuern":                                                    {Key: "aktiva.D"},
	"bilanz.passiva_a_i.kapitalanteil_der_persoenlich_haftenden":                                {Key: "passiva.A.I", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_i.anfangskapital":                                                         {Key: "passiva.A.I", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_i.verbindlichkeiten_gegenueber_persoenlich":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_i.kapitalanteile_der_kommanditisten":                                      {Key: "passiva.A.I", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_i.verbindlichkeiten_gegenueber_kommanditis":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_privat_vollhafter.kapitalanteil_der_persoenlich_haftenden":                {Key: "passiva.A.I", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_a_privat_vollhafter.entnahmen":                                              {Key: "passiva.A.I", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_d_8_privat_teilhafter.entnahmen":                                            {Key: "passiva.C.8", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_d_8_privat_teilhafter.privatkonten_teilhafter_kommanditisten_f":             {Key: "passiva.C.8", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_b.gezeichnetes_kapital":                                                     {Key: "passiva.A.I"},
	"bilanz.passiva_b.geschaeftsguthaben_der_verbleibenden_mit":                                 {Key: "passiva.A.I", Note: "Position der Genossenschaft (§ 337 HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_b.geschaeftsguthaben_der_ausscheidenden_mi":                                 {Key: "passiva.A.I", Note: "Position der Genossenschaft (§ 337 HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_b.geschaeftsguthaben_aus_gekuendigten_gesc":                                 {Key: "passiva.A.I", Note: "Position der Genossenschaft (§ 337 HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_b.eigene_anteile":                                                           {Key: "passiva.A.I", Deduction: true, Note: "Eigene Anteile werden nach § 272 Abs. 1a HGB offen vom gezeichneten Kapital abgesetzt."},
	"bilanz.passiva_b.nicht_eingeforderte_ausstehende_einlagen":                                 {Key: "passiva.A.I", Deduction: true, Note: "Nicht eingeforderte ausstehende Einlagen werden nach § 272 Abs. 1 Satz 3 HGB offen vom gezeichneten Kapital abgesetzt."},
	"bilanz.passiva_a_ii.kapitalruecklage":                                                      {Key: "passiva.A.II"},
	"bilanz.passiva_a_iii.gesetzliche_ruecklage":                                                {Key: "passiva.A.III.1"},
	"bilanz.passiva_a_iii.ruecklage_fuer_anteile_an_einem_herrsche":                             {Key: "passiva.A.III.2"},
	"bilanz.passiva_a_iii.andere_ergebnisruecklagen":                                            {Key: "passiva.A.III.4"},
	"bilanz.passiva_a_iii.satzungsmaessige_ruecklagen":                                          {Key: "passiva.A.III.3"},
	"bilanz.passiva_a_iii.ruecklagen":                                                           {Key: "passiva.A.III.4"},
	"bilanz.passiva_a_iii.andere_gewinnruecklagen":                                              {Key: "passiva.A.III.4"},
	"bilanz.passiva_a_iii.anfangskapital":                                                       {Key: "passiva.A.III.4", Note: "Gewinnrücklagen aus den Übergangsvorschriften des BilMoG und die darin verrechneten latenten Steuern (Konten 2963 bis 2969). Die Bezeichnung der Katalogposition ist verschoben; der hgb_code Passiva.A.III und die Konten weisen sie als Gewinnrücklage aus."},
	"bilanz.passiva_a_iv.gewinn_verlustvortrag":                                                 {Key: "passiva.A.IV"},
	"bilanz.passiva_a_iv.gewinn_verlustvortrag_vor_verwendung":                                  {Key: "passiva.A.IV"},
	"bilanz.passiva_a_v.andere_sonderposten":                                                    {Key: "passiva.SP"},
	"bilanz.passiva_a_v.sonderposten_mit_ruecklageanteil":                                       {Key: "passiva.SP"},
	"bilanz.passiva_a_v.sonderposten_fuer_zuschuesse_und_zulagen":                               {Key: "passiva.SP"},
	"bilanz.passiva_c_1.rueckstellungen_fuer_pensionen_und_aehnl":                               {Key: "passiva.B.1"},
	"bilanz.passiva_c_2.steuerrueckstellungen":                                                  {Key: "passiva.B.2"},
	"bilanz.passiva_c_2.rueckstellung_fuer_latente_steuern":                                     {Key: "passiva.E"},
	"bilanz.passiva_c_2.passive_latente_steuern":                                                {Key: "passiva.E"},
	"bilanz.passiva_c_3.sonstige_rueckstellungen":                                               {Key: "passiva.B.3"},
	"bilanz.passiva_c_3.sonstige_rueckstellungen_oder_aktiver_un":                               {Key: "passiva.B.3", AltKey: "aktiva.E"},
	"bilanz.passiva_d_1.anleihen":                                                               {Key: "passiva.C.1"},
	"bilanz.passiva_d_2.verbindlichkeiten_gegenueber_kreditinsti":                               {Key: "passiva.C.2", AltKey: "aktiva.B.IV"},
	"bilanz.passiva_d_3.erhaltene_anzahlungen_auf_bestellungen":                                 {Key: "passiva.C.3"},
	"bilanz.passiva_d_4.verbindlichkeiten_aus_lieferungen_und_le":                               {Key: "passiva.C.4", AltKey: "aktiva.B.II.1"},
	"bilanz.passiva_d_4.andere_verbindlichkeiten_gegenueber_gese":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_4.verbindlichkeiten_aus_der_annahme_gezoge":                               {Key: "passiva.C.5"},
	"bilanz.passiva_d_4.verbindlichkeiten_gegenueber_verbundenen":                               {Key: "passiva.C.6", AltKey: "aktiva.B.II.2"},
	"bilanz.passiva_d_4.verbindlichkeiten_gegenueber_unternehmen":                               {Key: "passiva.C.7", AltKey: "aktiva.B.II.3"},
	"bilanz.passiva_d_5.sonstige_verbindlichkeiten_oder_sonstige":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_5.sonstige_verbindlichkeiten":                                             {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_5.andere_verbindlichkeiten_gegenueber_gese":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_6.sonstige_verbindlichkeiten":                                             {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_7.sonstige_verbindlichkeiten_oder_sonstige":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_7.sonstige_verbindlichkeiten":                                             {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_8.verbindlichkeiten_gegenueber_gesellschaf":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_8.verbindlichkeiten_gegenueber_persoenlich":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_d_8.verbindlichkeiten_gegenueber_kommanditis":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4", Note: "Position der Personenhandelsgesellschaft (§ 264c HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"bilanz.passiva_d_8.sonstige_verbindlichkeiten":                                             {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_8.sonstige_vermoegensgegenstaende_h_saldo":                                {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_8.sonstige_verbindlichkeiten_oder_sonstige":                               {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_d_8.sonstige_verbindlichkeiten_inkl_steuern":                                {Key: "passiva.C.8", AltKey: "aktiva.B.II.4"},
	"bilanz.passiva_e.rechnungsabgrenzungsposten":                                               {Key: "passiva.D"},
	"bilanz.passiva_f.rechnungsabgrenzungsposten":                                               {Key: "passiva.E"},
	"guv.guv_1.umsatzerloese":                                                                   {Key: "guv.1"},
	"guv.guv_2.erhoehung_oder_verminderung_des_bestands":                                        {Key: "guv.1", Note: "Unentgeltliche Wertabgaben, Innenumsätze und die direkt mit dem Umsatz verbundenen Steuern (Konten 4600 bis 4699). Sie gehören nach der DATEV-Zuordnung des SKR04 zu den Umsatzerlösen, nicht zu den Bestandsveränderungen; die Bezeichnung der Katalogposition ist um eine Zeile verschoben."},
	"guv.guv_3.andere_aktivierte_eigenleistungen":                                               {Key: "guv.1", Note: "Erlösschmälerungen, gewährte Skonti, Boni und Rabatte (Konten 4700 bis 4799). Sie sind nach § 277 Abs. 1 HGB von den Umsatzerlösen abzusetzen; ihr Sollsaldo mindert deshalb die Zeile Nr. 1."},
	"guv.guv_4.erhoehung_oder_verminderung_des_bestande":                                        {Key: "guv.2"},
	"guv.guv_4.andere_aktivierte_eigenleistungen":                                               {Key: "guv.3"},
	"guv.guv_4.sonstige_betriebliche_ertraege":                                                  {Key: "guv.4"},
	"guv.guv_4.umsatzerloese":                                                                   {Key: "guv.4", Note: "Nebenerlöse, Erträge aus Währungsumrechnung und Erlöse aus dem Verkauf von Anlagevermögen (Konten 4833 bis 4849, 4992). Sie sind keine Umsatzerlöse im Sinne des § 277 Abs. 1 HGB, weil sie nicht aus dem Verkauf oder der Vermietung von Erzeugnissen und Leistungen stammen."},
	"guv.guv_5_a.aufwendungen_fuer_roh_hilfs_und_betriebs":                                      {Key: "guv.5.a"},
	"guv.guv_5_b.aufwendungen_fuer_bezogene_leistungen_fr":                                      {Key: "guv.5.b"},
	"guv.guv_6_a.loehne_und_gehaelter":                                                          {Key: "guv.6.a"},
	"guv.guv_6_b.soziale_abgaben_und_aufwendungen_fuer_al":                                      {Key: "guv.6.b"},
	"guv.guv_7_a.soziale_abgaben_und_aufwendungen_fuer_al":                                      {Key: "guv.7.a", Note: "Abschreibungen auf immaterielle Vermögensgegenstände, Gebäude und Sachanlagen (Konten 6200 bis 6231). Die Bezeichnung der Katalogposition wiederholt die der vorangehenden Zeile."},
	"guv.guv_7_a.abschreibungen_auf_immaterielle_vermoege":                                      {Key: "guv.7.a"},
	"guv.guv_7_b.abschreibung_auf_vermoegensgegenstaende":                                       {Key: "guv.7.b"},
	"guv.guv_8.sonstige_betriebliche_aufwendungen":                                              {Key: "guv.8"},
	"guv.guv_8.genossenschaftliche_rueckverguetung":                                             {Key: "guv.8", Note: "Position der Genossenschaft (§ 337 HGB); hier in der Gliederung der Kapitalgesellschaft ausgewiesen."},
	"guv.guv_9.ertraege_aus_beteiligungen":                                                      {Key: "guv.9"},
	"guv.guv_9.ertraege_aus_anderen_wertpapieren_und_au":                                        {Key: "guv.10"},
	"guv.guv_11.sonstige_zinsen_und_aehnliche_ertraege":                                         {Key: "guv.11"},
	"guv.guv_11.sonstige_zinsen_und_aehnliche_ertraege_o":                                       {Key: "guv.11", AltKey: "guv.13"},
	"guv.guv_11.ertraege_aus_verlustuebernahme":                                                 {Key: "guv.11a"},
	"guv.guv_11.auf_grund_einer_gewinngemeinschaft_eines":                                       {Key: "guv.11a"},
	"guv.guv_ertragverlustuebernahme.abschreibungen_auf_finanzanlagen_und_auf":                  {Key: "guv.12"},
	"guv.guv_12.abschreibungen_auf_finanzanlagen_und_auf":                                       {Key: "guv.13"},
	"guv.guv_12.abschreibungen_auf_finanzanlagen_und_wer":                                       {Key: "guv.13"},
	"guv.guv_12.zinsen_und_aehnliche_aufwendungen_oder_s":                                       {Key: "guv.13", AltKey: "guv.11"},
	"guv.guv_12.zinsen_und_aehnliche_aufwendungen":                                              {Key: "guv.13"},
	"guv.guv_12.aufwendungen_aus_verlustuebernahme_mutte":                                       {Key: "guv.13a"},
	"guv.guv_12.auf_grund_einer_gewinngemeinschaft_eines":                                       {Key: "guv.13a"},
	"guv.guv_13.sonstige_betriebliche_ertraege":                                                 {Key: "guv.4"},
	"guv.guv_aufwandverlustuebernahme.sonstige_betriebliche_aufwendungen":                       {Key: "guv.8"},
	"guv.guv_14.steuern_vom_einkommen_und_ertrag":                                               {Key: "guv.14"},
	"guv.guv_14.steuern_vom_einkommen_und_vom_ertrag_ode":                                       {Key: "guv.14"},
	"guv.guv_14.steuern_vom_einkommen_und_vom_ertrag":                                           {Key: "guv.14"},
	"guv.guv_14.sonstige_steuern":                                                               {Key: "guv.16"},
	"guv.guv_16.davon_gewinn_verlustvortrag":                                                    {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_der_kapitalruecklage":                                             {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_der_gesetzlichen_ruecklage":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_der_ruecklage_fuer_anteile":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_anderen_ergebnisruecklagen":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_satzungsmaessigen_ruecklag":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_anderen_gewinnruecklagen":                                         {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.entnahmen_aus_anderen_ruecklagen":                                               {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.ertrag_aus_kapitalherabsetzung":                                                 {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellung_in_die_kapitalruecklage_nach":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_die_gesetzliche_rueckla":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_die_ruecklage_fuer_ante":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_satzungsmaessige_rueckl":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_andere_gewinnruecklagen":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_andere_ruecklagen":                                             {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.einstellungen_in_andere_ergebnisruecklag":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.steuerliches_mehr_minderergebnis_lfd_jah":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_16.vorabausschuettung_beschlossene_ausschue":                                       {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_ergebnisverwendung.sonstige_betriebliche_aufwendungen":                             {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"guv.guv_kuenftigeverwendung.sonstige_betriebliche_aufwendungen":                            {Key: "passiva.A.VI", Note: "Konto der Ergebnisverwendung (§ 268 Abs. 1 HGB); es gehört nicht in die Gewinn- und Verlustrechnung nach § 275 HGB."},
	"statistisch.statistisch_vortragskonten.saldenvortragskonten":                               {Key: "statistisch"},
	"statistisch.statistisch_bwa.statistische_konten_fuer_bwa":                                  {Key: "statistisch"},
	"statistisch.statistisch_bwa.kapitalanteile_der_kommanditisten":                             {Key: "statistisch"},
	"statistisch.statistisch_bwa.sammelposten_anrechenbare_steuern":                             {Key: "statistisch"},
	"statistisch.statistisch_bwa.kapitalanteil_der_persoenlich_haftenden":                       {Key: "statistisch"},
	"statistisch.statistisch_bwa.nicht_eingeforderte_ausstehende_einlagen":                      {Key: "statistisch"},
	"statistisch.statistisch_bwa.verbindlichkeiten_gegenueber_kommanditis":                      {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.statistische_konten_fuer_kapitalflussrec":             {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.steuerliches_mehr_minderergebnis_lfd_jah":             {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.verbindlichkeiten_aus_lieferungen_und_le":             {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.sonstige_verbindlichkeiten":                           {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.einlagen_stiller_gesellschafter":                      {Key: "statistisch"},
	"statistisch.statistisch_kapitalfluss.steuerlicher_ausgleichsposten":                        {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.steuerlicher_ausgleichsposten":            {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.statistische_konten_fuer_kapitalkontenen": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.kapitalanteil_der_persoenlich_haftenden":  {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.verbindlichkeiten_gegenueber_persoenlich": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.eingeforderte_noch_ausstehende_kapitalei": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.kapitalanteile_der_kommanditisten":        {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.verbindlichkeiten_gegenueber_kommanditis": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.gutschrift_auf_kapitalkonten_oder_ergebn": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.kapitalanteil_persoenlich_haftende_gesel": {Key: "statistisch"},
	"statistisch.statistisch_kapitalkontenentwicklung.kapitalanteil_kommanditisten_kapco":       {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.ruecklagen":                                     {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.gewinn_verlustvortrag_vor_verwendung":           {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.kapitalanteil_der_persoenlich_haftenden":        {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.kapitalanteile_der_kommanditisten":              {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.einzahlungsverpflichtungen_persoenlich_h":       {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.einzahlungsverpflichtungen_kommanditiste":       {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.ausgleichsposten_fuer_aktivierte_eigene":        {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.nicht_durch_vermoegenseinlagen_gedeckte":        {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.durch_verluste_entstandenes_negatives_ka":       {Key: "statistisch"},
	"statistisch.statistisch_gewinnzuschlagestg.statistische_konten_fuer_gewinnzuschlag":        {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.ruecklagen":                                    {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.statistische_konten_fuer_7g_estg_gewinnk":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.forderungen_aus_lieferungen_und_leistung":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.sonstige_verbindlichkeiten":                    {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.kassenbestand_bundesbankguthaben_guthabe":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.verbindlichkeiten_gegenueber_kreditinsti":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.verbindlichkeiten_aus_lieferungen_und_le":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.sonstige_vermoegensgegenstaende":               {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.gutschrift_auf_verbindlichkeitskonten_od":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.gutschrift_auf_kapitalkonten_oder_ergebn":      {Key: "statistisch"},
	"statistisch.statistisch_investitionsabzug7g.":                                              {Key: "statistisch"},
}
