package einvoice

// The rule inventory of EN 16931.
//
// Every business rule the standard defines for the semantic model, together
// with the business terms it is about and whether the standard treats it as
// fatal. It exists so three questions can be answered by machine instead of by
// assertion: which rules exist, which of them Buchfink checks, and which field
// a finding is pointing at.
//
// Only identifiers are kept — rule numbers and business term numbers. They are
// facts about the standard. The rule texts belong to the validation artefact of
// the European Commission, which is licensed under EUPL-1.2 while Buchfink is
// under MIT.
//
// Erzeugt aus: ConnectingEurope/eInvoicing-EN16931 — Kontext und Schweregrad
// aus dem abstrakten Regelsatz, die Begriffsnummern zusätzlich aus der
// CII-Bindung, weil zwei Regeln sie im abstrakten Text nicht nennen.

// RuleInfo describes one business rule of the standard.
type RuleInfo struct {
	// Context is the business group the rule hangs off, in the standard's own
	// naming — "Document_totals", "VAT_breakdown", "Invoice_Line".
	Context string
	// Terms are the business terms (BT/BG) the rule speaks about. A caller can
	// point the user at the field instead of making them decode a rule number.
	Terms []string
	// Fatal says whether the standard flags a violation as fatal. One rule is a
	// warning there, and Buchfink keeps that distinction rather than inventing
	// its own.
	Fatal bool
}

// en16931Rules is the complete inventory, keyed by rule identifier.
var en16931Rules = map[string]RuleInfo{
	"BR-01":     {Context: "Invoice", Terms: []string{"BT-24"}, Fatal: true},
	"BR-02":     {Context: "Invoice", Terms: []string{"BT-1"}, Fatal: true},
	"BR-03":     {Context: "Invoice", Terms: []string{"BT-2"}, Fatal: true},
	"BR-04":     {Context: "Invoice", Terms: []string{"BT-3"}, Fatal: true},
	"BR-05":     {Context: "Invoice", Terms: []string{"BT-5"}, Fatal: true},
	"BR-06":     {Context: "Invoice", Terms: []string{"BT-27"}, Fatal: true},
	"BR-07":     {Context: "Invoice", Terms: []string{"BT-44"}, Fatal: true},
	"BR-08":     {Context: "Invoice", Terms: []string{"BG-5"}, Fatal: true},
	"BR-09":     {Context: "Seller_postal_address", Terms: []string{"BG-5", "BT-40"}, Fatal: true},
	"BR-10":     {Context: "Invoice", Terms: []string{"BG-8"}, Fatal: true},
	"BR-11":     {Context: "Buyer_postal_address", Terms: []string{"BT-55"}, Fatal: true},
	"BR-12":     {Context: "Document_totals", Terms: []string{"BT-106"}, Fatal: true},
	"BR-13":     {Context: "Document_totals", Terms: []string{"BT-109"}, Fatal: true},
	"BR-14":     {Context: "Document_totals", Terms: []string{"BT-112"}, Fatal: true},
	"BR-15":     {Context: "Document_totals", Terms: []string{"BT-115"}, Fatal: true},
	"BR-16":     {Context: "Invoice", Terms: []string{"BG-25"}, Fatal: true},
	"BR-17":     {Context: "Payee", Terms: []string{"BG-10", "BG-4", "BT-59"}, Fatal: true},
	"BR-18":     {Context: "Tax_Representative", Terms: []string{"BG-11", "BG-4", "BT-62"}, Fatal: true},
	"BR-19":     {Context: "Tax_Representative", Terms: []string{"BG-11", "BG-12", "BG-4"}, Fatal: true},
	"BR-20":     {Context: "Tax_Representative_postal_address", Terms: []string{"BG-11", "BG-12", "BG-4", "BT-69"}, Fatal: true},
	"BR-21":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-126"}, Fatal: true},
	"BR-22":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-129"}, Fatal: true},
	"BR-23":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-130"}, Fatal: true},
	"BR-24":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-131"}, Fatal: true},
	"BR-25":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-153"}, Fatal: true},
	"BR-26":     {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-146"}, Fatal: true},
	"BR-27":     {Context: "Invoice_Line", Terms: []string{"BT-146"}, Fatal: true},
	"BR-28":     {Context: "Invoice_Line", Terms: []string{"BT-148"}, Fatal: true},
	"BR-29":     {Context: "Invoice_Period", Terms: []string{"BT-73", "BT-74"}, Fatal: true},
	"BR-30":     {Context: "Invoice_Line_Period", Terms: []string{"BT-134", "BT-135"}, Fatal: true},
	"BR-31":     {Context: "Document_level_allowances", Terms: []string{"BG-20", "BT-92"}, Fatal: true},
	"BR-32":     {Context: "Document_level_allowances", Terms: []string{"BG-20", "BT-95"}, Fatal: true},
	"BR-33":     {Context: "Document_level_allowances", Terms: []string{"BG-20", "BT-97", "BT-98"}, Fatal: true},
	"BR-36":     {Context: "Document_level_charges", Terms: []string{"BG-21", "BT-99"}, Fatal: true},
	"BR-37":     {Context: "Document_level_charges", Terms: []string{"BG-21", "BT-102"}, Fatal: true},
	"BR-38":     {Context: "Document_level_charges", Terms: []string{"BG-21", "BT-104", "BT-105"}, Fatal: true},
	"BR-41":     {Context: "Invoice_line_allowances", Terms: []string{"BG-27", "BT-136"}, Fatal: true},
	"BR-42":     {Context: "Invoice_line_allowances", Terms: []string{"BG-27", "BT-139", "BT-140"}, Fatal: true},
	"BR-43":     {Context: "Invoice_line_charges", Terms: []string{"BG-28", "BT-141"}, Fatal: true},
	"BR-44":     {Context: "Invoice_line_charges", Terms: []string{"BG-28", "BT-144", "BT-145"}, Fatal: true},
	"BR-45":     {Context: "VAT_breakdown", Terms: []string{"BG-23", "BT-116"}, Fatal: true},
	"BR-46":     {Context: "VAT_breakdown", Terms: []string{"BG-23", "BT-117"}, Fatal: true},
	"BR-47":     {Context: "VAT_breakdown", Terms: []string{"BG-23", "BT-118"}, Fatal: true},
	"BR-48":     {Context: "VAT_breakdown", Terms: []string{"BG-23", "BT-119"}, Fatal: true},
	"BR-49":     {Context: "Payment_instructions", Terms: []string{"BG-16", "BT-81"}, Fatal: true},
	"BR-50":     {Context: "Payee_Financial_Account", Terms: []string{"BG-16", "BG-17", "BT-84"}, Fatal: true},
	"BR-51":     {Context: "Card_information", Terms: []string{"BT-87", "BT-97"}, Fatal: false},
	"BR-52":     {Context: "Additional_supporting_documents", Terms: []string{"BG-24", "BT-122"}, Fatal: true},
	"BR-53":     {Context: "Invoice", Terms: []string{"BT-111", "BT-6"}, Fatal: true},
	"BR-54":     {Context: "Item_attributes", Terms: []string{"BG-32", "BT-160", "BT-161"}, Fatal: true},
	"BR-55":     {Context: "Preceding_Invoice", Terms: []string{"BG-3", "BT-25"}, Fatal: true},
	"BR-56":     {Context: "Tax_Representative", Terms: []string{"BG-11", "BT-63"}, Fatal: true},
	"BR-57":     {Context: "Deliver_to_address", Terms: []string{"BG-15", "BT-80"}, Fatal: true},
	"BR-61":     {Context: "Payment_instructions", Terms: []string{"BT-81", "BT-84"}, Fatal: true},
	"BR-62":     {Context: "Seller_electronic_address", Terms: []string{"BT-34"}, Fatal: true},
	"BR-63":     {Context: "Buyer_electronic_address", Terms: []string{"BT-49"}, Fatal: true},
	"BR-64":     {Context: "Item_standard_identifier", Terms: []string{"BT-157"}, Fatal: true},
	"BR-65":     {Context: "Item_classification_identifier", Terms: []string{"BT-158"}, Fatal: true},
	"BR-AE-01":  {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-AE-02":  {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63"}, Fatal: true},
	"BR-AE-03":  {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63", "BT-95"}, Fatal: true},
	"BR-AE-04":  {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-47", "BT-48", "BT-63"}, Fatal: true},
	"BR-AE-05":  {Context: "VATAE_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-AE-06":  {Context: "VATAE_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-AE-07":  {Context: "VATAE_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-AE-08":  {Context: "VATAE", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-AE-09":  {Context: "VATAE", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-AE-10":  {Context: "VATAE", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-AF-01":  {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-AF-02":  {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-AF-03":  {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"}, Fatal: true},
	"BR-AF-04":  {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-AF-05":  {Context: "VATIG_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-AF-06":  {Context: "VATIG_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-AF-07":  {Context: "VATIG_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-AF-08":  {Context: "VATIG", Terms: []string{"BG-23", "BT-102", "BT-103", "BT-116", "BT-118", "BT-119", "BT-131", "BT-151", "BT-152", "BT-92", "BT-95", "BT-96", "BT-99"}, Fatal: true},
	"BR-AF-09":  {Context: "VATIG", Terms: []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"}, Fatal: true},
	"BR-AF-10":  {Context: "VATIG", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-AG-01":  {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-AG-02":  {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-AG-03":  {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"}, Fatal: true},
	"BR-AG-04":  {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-AG-05":  {Context: "VATIP_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-AG-06":  {Context: "VATIP_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-AG-07":  {Context: "VATIP_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-AG-08":  {Context: "VATIP", Terms: []string{"BG-23", "BT-102", "BT-103", "BT-116", "BT-118", "BT-119", "BT-131", "BT-151", "BT-152", "BT-92", "BT-95", "BT-96", "BT-99"}, Fatal: true},
	"BR-AG-09":  {Context: "VATIP", Terms: []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"}, Fatal: true},
	"BR-AG-10":  {Context: "VATIP", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-B-01":   {Context: "Invoice", Terms: []string{"BT-102", "BT-151", "BT-95"}, Fatal: true},
	"BR-B-02":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-CL-01":  {Context: "rsm:ExchangedDocument/ram:TypeCode", Terms: nil, Fatal: true},
	"BR-CL-03":  {Context: "ram:TaxTotalAmount[@currencyID]", Terms: nil, Fatal: true},
	"BR-CL-04":  {Context: "ram:InvoiceCurrencyCode", Terms: nil, Fatal: true},
	"BR-CL-05":  {Context: "ram:TaxCurrencyCode", Terms: nil, Fatal: true},
	"BR-CL-06":  {Context: "ram:DueDateTypeCode", Terms: nil, Fatal: true},
	"BR-CL-07":  {Context: "ram:ReferenceTypeCode", Terms: nil, Fatal: true},
	"BR-CL-08":  {Context: "ram:SubjectCode", Terms: nil, Fatal: true},
	"BR-CL-10":  {Context: "//ram:GlobalID[@schemeID][not(ancestor::ram:SpecifiedTradeProduct) and not(ancestor::ram:ShipToTradeParty)]", Terms: nil, Fatal: true},
	"BR-CL-11":  {Context: "ram:ID[@schemeID][not(ancestor::ram:SpecifiedTaxRegistration)]", Terms: nil, Fatal: true},
	"BR-CL-13":  {Context: "ram:ClassCode[@listID]", Terms: nil, Fatal: true},
	"BR-CL-14":  {Context: "ram:CountryID", Terms: nil, Fatal: true},
	"BR-CL-15":  {Context: "ram:OriginTradeCountry/ram:ID", Terms: nil, Fatal: true},
	"BR-CL-16":  {Context: "ram:SpecifiedTradeSettlementPaymentMeans/ram:TypeCode", Terms: nil, Fatal: true},
	"BR-CL-17":  {Context: "ram:CategoryTradeTax/ram:CategoryCode", Terms: nil, Fatal: true},
	"BR-CL-18":  {Context: "ram:ApplicableTradeTax/ram:CategoryCode", Terms: nil, Fatal: true},
	"BR-CL-19":  {Context: "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator = false()]/ram:ReasonCode", Terms: nil, Fatal: true},
	"BR-CL-20":  {Context: "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator = true()]/ram:ReasonCode", Terms: nil, Fatal: true},
	"BR-CL-21":  {Context: "ram:SpecifiedTradeProduct/ram:GlobalID[@schemeID]", Terms: nil, Fatal: true},
	"BR-CL-22":  {Context: "ram:ExemptionReasonCode", Terms: nil, Fatal: true},
	"BR-CL-23":  {Context: "ram:BasisQuantity[@unitCode] | ram:BilledQuantity[@unitCode]", Terms: nil, Fatal: true},
	"BR-CL-24":  {Context: "ram:AttachmentBinaryObject[@mimeCode]", Terms: nil, Fatal: true},
	"BR-CL-25":  {Context: "ram:URIUniversalCommunication/ram:URIID[@schemeID]", Terms: nil, Fatal: true},
	"BR-CL-26":  {Context: "ram:ApplicableHeaderTradeDelivery/ram:ShipToTradeParty/ram:GlobalID[@schemeID]", Terms: nil, Fatal: true},
	"BR-CO-03":  {Context: "Invoice", Terms: []string{"BT-7", "BT-8"}, Fatal: true},
	"BR-CO-04":  {Context: "Invoice_Line", Terms: []string{"BG-25", "BT-151"}, Fatal: true},
	"BR-CO-05":  {Context: "Document_level_allowances", Terms: []string{"BT-97", "BT-98"}, Fatal: true},
	"BR-CO-06":  {Context: "Document_level_charges", Terms: []string{"BT-104", "BT-105"}, Fatal: true},
	"BR-CO-07":  {Context: "Invoice_line_allowances", Terms: []string{"BT-139", "BT-140"}, Fatal: true},
	"BR-CO-08":  {Context: "Invoice_line_charges", Terms: []string{"BT-144", "BT-145"}, Fatal: true},
	"BR-CO-09":  {Context: "VAT_identifiers", Terms: []string{"BT-31", "BT-48", "BT-63"}, Fatal: true},
	"BR-CO-10":  {Context: "Document_totals", Terms: []string{"BT-106", "BT-131"}, Fatal: true},
	"BR-CO-11":  {Context: "Document_totals", Terms: []string{"BT-107", "BT-92"}, Fatal: true},
	"BR-CO-12":  {Context: "Document_totals", Terms: []string{"BT-108", "BT-99"}, Fatal: true},
	"BR-CO-13":  {Context: "Document_totals", Terms: []string{"BT-107", "BT-108", "BT-109", "BT-131"}, Fatal: true},
	"BR-CO-14":  {Context: "Tax_Total", Terms: []string{"BT-110", "BT-117"}, Fatal: true},
	"BR-CO-15":  {Context: "Invoice", Terms: []string{"BT-109", "BT-110", "BT-112"}, Fatal: true},
	"BR-CO-16":  {Context: "Document_totals", Terms: []string{"BT-112", "BT-113", "BT-114", "BT-115"}, Fatal: true},
	"BR-CO-17":  {Context: "VAT_breakdown", Terms: []string{"BT-116", "BT-117", "BT-119"}, Fatal: true},
	"BR-CO-18":  {Context: "Invoice", Terms: []string{"BG-23"}, Fatal: true},
	"BR-CO-19":  {Context: "Invoice_Period", Terms: []string{"BG-14", "BT-73", "BT-74"}, Fatal: true},
	"BR-CO-20":  {Context: "Invoice_Line_Period", Terms: []string{"BG-26", "BT-134", "BT-135"}, Fatal: true},
	"BR-CO-21":  {Context: "Document_level_allowances", Terms: []string{"BG-20", "BT-97", "BT-98"}, Fatal: true},
	"BR-CO-22":  {Context: "Document_level_charges", Terms: []string{"BG-21", "BT-104", "BT-105"}, Fatal: true},
	"BR-CO-23":  {Context: "Invoice_line_allowances", Terms: []string{"BG-27", "BT-139", "BT-140"}, Fatal: true},
	"BR-CO-24":  {Context: "Invoice_line_charges", Terms: []string{"BG-28", "BT-144", "BT-145"}, Fatal: true},
	"BR-CO-26":  {Context: "Seller", Terms: []string{"BT-29", "BT-30", "BT-31"}, Fatal: true},
	"BR-DEC-01": {Context: "Document_level_allowances", Terms: []string{"BT-92"}, Fatal: true},
	"BR-DEC-02": {Context: "Document_level_allowances", Terms: []string{"BT-93"}, Fatal: true},
	"BR-DEC-05": {Context: "Document_level_charges", Terms: []string{"BT-99"}, Fatal: true},
	"BR-DEC-06": {Context: "Document_level_charges", Terms: []string{"BT-100"}, Fatal: true},
	"BR-DEC-09": {Context: "Document_totals", Terms: []string{"BT-106"}, Fatal: true},
	"BR-DEC-10": {Context: "Document_totals", Terms: []string{"BT-107"}, Fatal: true},
	"BR-DEC-11": {Context: "Document_totals", Terms: []string{"BT-108"}, Fatal: true},
	"BR-DEC-12": {Context: "Document_totals", Terms: []string{"BT-109"}, Fatal: true},
	"BR-DEC-13": {Context: "Invoice", Terms: []string{"BT-110"}, Fatal: true},
	"BR-DEC-14": {Context: "Document_totals", Terms: []string{"BT-112"}, Fatal: true},
	"BR-DEC-15": {Context: "Invoice", Terms: []string{"BT-111"}, Fatal: true},
	"BR-DEC-16": {Context: "Document_totals", Terms: []string{"BT-113"}, Fatal: true},
	"BR-DEC-17": {Context: "Document_totals", Terms: []string{"BT-114"}, Fatal: true},
	"BR-DEC-18": {Context: "Document_totals", Terms: []string{"BT-115"}, Fatal: true},
	"BR-DEC-19": {Context: "VAT_breakdown", Terms: []string{"BT-116"}, Fatal: true},
	"BR-DEC-20": {Context: "VAT_breakdown", Terms: []string{"BT-117"}, Fatal: true},
	"BR-DEC-23": {Context: "Invoice_Line", Terms: []string{"BT-131"}, Fatal: true},
	"BR-DEC-24": {Context: "Invoice_line_allowances", Terms: []string{"BT-136"}, Fatal: true},
	"BR-DEC-25": {Context: "Invoice_line_allowances", Terms: []string{"BT-137"}, Fatal: true},
	"BR-DEC-27": {Context: "Invoice_line_charges", Terms: []string{"BT-141"}, Fatal: true},
	"BR-DEC-28": {Context: "Invoice_line_charges", Terms: []string{"BT-142"}, Fatal: true},
	"BR-E-01":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-E-02":   {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-E-03":   {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"}, Fatal: true},
	"BR-E-04":   {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-E-05":   {Context: "VATE_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-E-06":   {Context: "VATE_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-E-07":   {Context: "VATE_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-E-08":   {Context: "VATE", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-E-09":   {Context: "VATE", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-E-10":   {Context: "VATE", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-G-01":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-G-02":   {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-63"}, Fatal: true},
	"BR-G-03":   {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-63", "BT-95"}, Fatal: true},
	"BR-G-04":   {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-63"}, Fatal: true},
	"BR-G-05":   {Context: "VATG_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-G-06":   {Context: "VATG_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-G-07":   {Context: "VATG_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-G-08":   {Context: "VATG", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-G-09":   {Context: "VATG", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-G-10":   {Context: "VATG", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-IC-01":  {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-IC-02":  {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-48", "BT-63"}, Fatal: true},
	"BR-IC-03":  {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-48", "BT-63", "BT-95"}, Fatal: true},
	"BR-IC-04":  {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-48", "BT-63"}, Fatal: true},
	"BR-IC-05":  {Context: "VATIC_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-IC-06":  {Context: "VATIC_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-IC-07":  {Context: "VATIC_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-IC-08":  {Context: "VATIC", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-IC-09":  {Context: "VATIC", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-IC-10":  {Context: "VATIC", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-IC-11":  {Context: "Invoice", Terms: []string{"BG-14", "BG-23", "BT-118", "BT-72"}, Fatal: true},
	"BR-IC-12":  {Context: "Invoice", Terms: []string{"BG-23", "BT-118", "BT-80"}, Fatal: true},
	"BR-O-01":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-O-02":   {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-48", "BT-63"}, Fatal: true},
	"BR-O-03":   {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-48", "BT-63", "BT-95"}, Fatal: true},
	"BR-O-04":   {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-48", "BT-63"}, Fatal: true},
	"BR-O-05":   {Context: "VATO_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-O-06":   {Context: "VATO_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-O-07":   {Context: "VATO_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-O-08":   {Context: "VATO", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-O-09":   {Context: "VATO", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-O-10":   {Context: "VATO", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-O-11":   {Context: "Invoice", Terms: []string{"BG-23", "BT-118"}, Fatal: true},
	"BR-O-12":   {Context: "Invoice", Terms: []string{"BG-23", "BG-25", "BT-118", "BT-151"}, Fatal: true},
	"BR-O-13":   {Context: "Invoice", Terms: []string{"BG-20", "BG-23", "BT-118", "BT-95"}, Fatal: true},
	"BR-O-14":   {Context: "Invoice", Terms: []string{"BG-21", "BG-23", "BT-102", "BT-118"}, Fatal: true},
	"BR-S-01":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-S-02":   {Context: "Invoice", Terms: []string{"BG-25", "BT-151", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-S-03":   {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"}, Fatal: true},
	"BR-S-04":   {Context: "Invoice", Terms: []string{"BG-21", "BT-102", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-S-05":   {Context: "VATS_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-S-06":   {Context: "VATS_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-S-07":   {Context: "VATS_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-S-08":   {Context: "VATS", Terms: []string{"BG-23", "BT-102", "BT-103", "BT-116", "BT-118", "BT-119", "BT-131", "BT-151", "BT-152", "BT-92", "BT-95", "BT-96", "BT-99"}, Fatal: true},
	"BR-S-09":   {Context: "VATS", Terms: []string{"BG-23", "BT-116", "BT-117", "BT-118", "BT-119"}, Fatal: true},
	"BR-S-10":   {Context: "VATS", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
	"BR-Z-01":   {Context: "Invoice", Terms: []string{"BG-20", "BG-21", "BG-23", "BG-25", "BT-102", "BT-118", "BT-151", "BT-95"}, Fatal: true},
	"BR-Z-02":   {Context: "Invoice", Terms: []string{"BT-151", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-Z-03":   {Context: "Invoice", Terms: []string{"BG-20", "BT-31", "BT-32", "BT-63", "BT-95"}, Fatal: true},
	"BR-Z-04":   {Context: "Invoice", Terms: []string{"BT-102", "BT-31", "BT-32", "BT-63"}, Fatal: true},
	"BR-Z-05":   {Context: "VATZ_Line", Terms: []string{"BG-25", "BT-151", "BT-152"}, Fatal: true},
	"BR-Z-06":   {Context: "VATZ_Allowance", Terms: []string{"BG-20", "BT-95", "BT-96"}, Fatal: true},
	"BR-Z-07":   {Context: "VATZ_Charge", Terms: []string{"BG-21", "BT-102", "BT-103"}, Fatal: true},
	"BR-Z-08":   {Context: "VATZ", Terms: []string{"BG-23", "BT-102", "BT-116", "BT-118", "BT-131", "BT-151", "BT-92", "BT-95", "BT-99"}, Fatal: true},
	"BR-Z-09":   {Context: "VATZ", Terms: []string{"BG-23", "BT-117", "BT-118"}, Fatal: true},
	"BR-Z-10":   {Context: "VATZ", Terms: []string{"BG-23", "BT-118", "BT-120", "BT-121"}, Fatal: true},
}
